language: java

jdk:
  - oraclejdk8

before_install:
  - chmod -R +x src
  - chmod +x gradlew

script:
  - ./gradlew clean build jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_KEY
  on:
    branch: master
